[project]
name = "FRC-2025"
version = "1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "photonlibpy",
    "mypy>=1.19.0",
    "robotpy[phoenix6]>=2025.3.2.2",
]


[tool.uv]
python-preference = "managed"
